server:
  port: 8400
  
spring:
    datasource:
<<<<<<< HEAD
        url: jdbc:mysql://118.190.202.148:3306/BUPT_IOT?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: Gantch815
=======
        url: jdbc:mysql://127.0.0.1:3306/bupt_iot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
>>>>>>> changed by rongshuai



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:  com.edu.bupt.new_account.model