server:
  port: 8400
  
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/bupt_iot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:  com.edu.bupt.new_account.model