server:
  port: 8080
  
spring:
    datasource:
        url: jdbc:mysql://10.108.218.108:3306/BUPT_IOT?useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package:  com.edu.bupt.new_account.model